version: 2.1

jobs:
  auto-tg-channel-ban-bot:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Auto Telegram Channel Ban Bot"
          command: "npm install telegraf && node index.js"
            

workflows:
  auto-tg-channel-ban-bot-workflow:
    jobs:
      - auto-tg-channel-ban-bot
